### ISSUE TITLE
Persistent connections

### ISSUE THREAD

**Issue by flavioheleno** [LinioIT/database#2]
Hi, I've gone through the code and couldn't find a way to use PDO::ATTR_PERSISTENT for persistent connections (should be passed as parameter to PDO constructor).

Did I miss anything or it is currently impossible to have persistent connections?

Thanks!

**Comment by camcima** [comment]
I've already implemented support for additional PDO connection attributes. We should have it merged today.

**Comment by camcima** [comment]
Please use latest version 1.0.4.
